### ISSUE TITLE
Storing received messages

### ISSUE THREAD

**Issue by 7jacks** [JanBoonen/TwsApiCpp#15]
Sorry I'm a rookie coder but was just wondering how one would store the received messages from TWS? 

For example, I'm using the Test.cpp and the program is receiving DelayedLast, DelayedBid etc. and I want to store that in a double to check for standard deviations etc. 

Any advice on how to deal with the incoming messages? Thanks!

**Comment by 7jacks** [comment]
Or an array*

**Comment by stevegee58** [comment]
If you want to do analysis on the data within the program use one of the std data containers like vector, map or list.  For offline analysis store them to a file using fstream.

**Comment by 7jacks** [comment]
Thanks for the prompt response!

And yes exactly, I want to do analysis within the program so that it can be done "real-time" (although for now it is delayed until I get a proper account)

And okay say I were to initialize a map containing the time and a vector<double> of the bid, ask etc. Im not quite sure how this would be done. Any thoughts?

Map<string, Vector<double>> timeToPrice; 
double lastPrice; // where is this information stored or how can it be stored?

**Comment by 7jacks** [comment]
Assuming I can declare properly haha 

    Map<string, Vector<double>> timeToPrice;
