### ISSUE TITLE
Visual Studio Linker Error LNK2019: unresolved external symbol public: static class EClientL0 

### ISSUE THREAD

**Issue by rholowczak** [JanBoonen/TwsApiCpp#3]
Environment: MS Windows 7 Pro, Visual Studio 2013. TwsApiCpp version 9.71.
When we open the TwsApi.sln solution there is a "One way upgrade" that produces the following warnings (two examples - there are a total of 12): 
..\Test_win32\Test.vcproj: Warning: The project file is being backed up to a relative path that differs from the original solution relative path. The difference in folder hierarchy may create problems in opening or building the backed up solution and project.
..\Test_win32\Test.vcproj: MSB8012: $(TargetPath) ('C:\Jts\TwsApiCpp\TwsApiC++\Test_win32.\Debug\Test.exe') does not match the Librarian's OutputFile property value '.\Debug\Test.exe' ('C:\Jts\TwsApiCpp\TwsApiC++_win32\Debug\Test.exe') in project configuration 'Debug|Win32'. This may cause your project to build incorrectly. To correct this, please make sure that $(TargetPath) property value matches the value specified in %(Lib.OutputFile). 

Issue: When building the "Test" project in Visual Studio 2013 (and possibly in other versions of VS), the following error appears on linking:

error LNK2019: unresolved external symbol "public: static class EClientL0 \* __cdecl EClientL0::New(class EWrapperL0 *)" (?New@EClientL0@@SAPAV1@PAVEWrapperL0@@@Z) referenced in function _main C:\Jts\TwsApiCpp\TwsApiC++\Test_win32\Empty.obj    Test

The solution appears to be:
1. Open up the Test Project Properties and then navigate to Configuration Properties -> Linker -> General. Add the full path the Api folder in the Additional Library Directories. For exmaple: C:\Jts\TwsApiCpp\TwsApiC++\Api
1. Open up the Test Project Properties and then navigate to Configuration Properties -> Linker -> Input. Add the TwsApi.lib file to the list that appears in Additional Dependencies.

I suspect it is just a matter of references to the Include and lib folders changing during the solution/project update to VS 2013.

**Comment by JanBoonen** [comment]
Indeed, this is a result of Visual Studio not correctly converting the project files of older versions. Probably, it should be closed?
